# Blocking Threshold
# IP addresses will be blocked when an incorrect account or password is entered within a specified period of time greater than a threshold value.
block_threshold: 3
# Blocking time in the seconds.
block_time: 600
workstation_name:
  # Check client workstation name when user logs in.
  # Block if it is different from the workstation name of the first login.
  # default: false
  check: false
  # Pre-bind workstation name
  user_bind:
    # Format
    # {UserName}: {WorkstationName}
    root: DESKTOP-0000000
  # Workstation name whitelist
  whitelist:
    - DESKTOP-0000000
log:
  # Log output level
  # The value can be:
  # trace debug info warning error critical off
  level: info
# Addresses in the whitelist will not be subject to any restrictions.
# Note that the expression is a regular expression.
IP_whitelist:
  - 127\.0\.0\..*
  - ^192\.168.*
  - ^172\.(1[6-9]|2[0-9]|3[0-1])\..*
  - ^10\..*