#ifndef __SELF_EXIT_CODE__
#define __SELF_EXIT_CODE__

enum EXIT_CODE{
	SUCCESS = 0,
	UNKNOW_ERROR = 10,
	CHECKSUM_ERROR,
	COMMAND_PARSE_ERROR,
	LOAD_CONFIG_ERROR,
	APP_EXIST_ERROR,
	FIREWALL_ERROR,
	SUBSCRIBE_EVENT_ERROR
};
#endif //__SELF_EXIT_CODE__